# Generated by Django 5.2.7 on 2025-10-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
