name: CI Django + DB + Docker

on:
  push:
    branches: ["database"]

jobs:
  # Django Test + DB Integration
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: nouchka/sqlite3  
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: python manage.py test

  #  Build Docker Image (only if tests pass)
  build_image:
    runs-on: ubuntu-latest
    needs: test 

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
             ankith1307/myprojct:${{ github.sha }}
