name: CI Django + DB + Docker

on:
  push:
    branches: ["database"]

jobs:
  test:
    runs-on: ubuntu-latest

    #setting up the mysql image
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Ankith@5space
          MYSQL_DATABASE: django
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    env: 
      GITHUB_WORKFLOW: true


    # entry to the repositry
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          sudo apt-get install -y default-mysql-client
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: python manage.py collectstatic --noinput
        

      - name: Run DB integration tests
        run: python manage.py test myapp.tests

  #  Build Docker Image (only if tests pass)
  build_image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ankith1307/myprojct:${{ github.sha }}
