name: Django CI with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t django-app .

    - name: Run Docker container
      run: docker run -d -p 8000:8000 --name django-test django-app

    - name: Test endpoint
      run: |
        sleep 10
        curl --fail http://localhost:8000
